---
# tasks file for lgblkb-deployer
- name: Configure docker output directories
  block:
    - name: Resolve volumes_dir
      set_fact:
        volumes_dir: "{{ [docker_data_dir,'volumes']|join('/') }}"

    - name: Create volumes_dir
      file:
        path: "{{ volumes_dir }}"
        state: 'directory'
        recurse: yes

  when: docker_data_dir|length!=0

- name: Deploy containers
  block:
    - name: Resolve defs_files
      set_fact:
        defs_files: "{{ query('fileglob',[container_defs_dir,'*']|join('/'))|sort() }}"

    - name: Read container configs
      include_tasks: "{{ item }}"
      with_fileglob: '{{ defs_files }}'

    - name: Collect container key-value pairs
      set_fact:
        container_info_keys: "{{ container_info_keys|default([])+[  ((item|basename|splitext)[0]).split('__')[1]  ] }}"
        container_info_values: "{{ container_info_values|default([])+[  lookup('vars',((item|basename|splitext)[0]).split('__')[1],default={})  ] }}"
      with_fileglob: '{{ defs_files }}'

    - name: Create container_infos
      set_fact:
        container_infos: "{{  container_infos|default({})|combine(dict(container_info_keys | zip(container_info_values)))  }}"
    #      notify: Deploy containers provided in definition files

    - name: Deploy containers provided in definition files
      include_tasks: "{{ container_template }}"
      loop: "{{  container_infos|dict2items(value_name='container')  }}"
      loop_control:
        loop_var: container_info
        index_var: loop_index

  when: container_defs_dir|length!=0
